apiVersion: v1
kind: ConfigMap
metadata:
  name: nyt-api-config
  namespace: nyt-news-api
  labels:
    app: nyt-api
    version: v1.0.0
data:
  NODE_ENV: "production"
  PORT: "3000"
  HOST: "0.0.0.0"
  
  # JWT Configuration
  JWT_ISSUER: "https://api.nyt-news-explorer.com"
  JWT_AUDIENCE: "nyt-news-explorer"
  JWT_ACCESS_TOKEN_TTL: "900"  # 15 minutes
  JWT_REFRESH_TOKEN_TTL: "2592000"  # 30 days
  
  # OAuth Configuration
  OAUTH_REDIRECT_URI: "https://app.nyt-news-explorer.com/auth/callback"
  OAUTH_AUTHORIZATION_URL: "https://accounts.google.com/o/oauth2/v2/auth"
  OAUTH_TOKEN_URL: "https://oauth2.googleapis.com/token"
  OAUTH_JWKS_URL: "https://www.googleapis.com/oauth2/v3/certs"
  
  # Rate Limiting
  RATE_LIMIT_MAX: "100"
  RATE_LIMIT_WINDOW_MS: "900000"  # 15 minutes
  RATE_LIMIT_SKIP_SUCCESS_HEADERS: "false"
  
  # Redis Configuration
  REDIS_HOST: "redis-service.redis-system.svc.cluster.local"
  REDIS_PORT: "6379"
  REDIS_DB: "0"
  
  # Observability
  OTEL_SERVICE_NAME: "nyt-news-api"
  OTEL_SERVICE_VERSION: "1.0.0"
  JAEGER_ENDPOINT: "http://jaeger-collector.monitoring.svc.cluster.local:14268/api/traces"
  LOG_LEVEL: "info"
  
  # TLS Configuration
  ENABLE_HTTP3: "false"  # Enable when cluster supports HTTP/3
  
  # CORS Configuration
  CORS_ORIGIN: "https://nyt.brainvaultdev.com,https://app.nyt-news-explorer.com"
  CORS_CREDENTIALS: "true"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nyt-api-nginx-config
  namespace: nyt-news-api
  labels:
    app: nyt-api-nginx
data:
  nginx.conf: |
    upstream api_backend {
        least_conn;
        server 127.0.0.1:3000 max_fails=3 fail_timeout=30s;
        keepalive 32;
    }
    
    # Rate limiting zones
    limit_req_zone $binary_remote_addr zone=api_limit:10m rate=10r/s;
    limit_req_zone $binary_remote_addr zone=auth_limit:10m rate=1r/s;
    limit_req_status 429;
    
    server {
        listen 8080;
        server_name _;
        
        # Security headers
        add_header X-Frame-Options DENY always;
        add_header X-Content-Type-Options nosniff always;
        add_header X-XSS-Protection "1; mode=block" always;
        add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload" always;
        add_header Referrer-Policy "strict-origin-when-cross-origin" always;
        
        # Compression
        gzip on;
        gzip_vary on;
        gzip_min_length 1024;
        gzip_types
            application/json
            application/javascript
            application/xml+rss
            application/atom+xml
            image/svg+xml
            text/css
            text/javascript
            text/xml
            text/plain;
        
        # Enable Brotli if available
        brotli on;
        brotli_comp_level 6;
        brotli_types
            application/json
            application/javascript
            text/css
            text/javascript
            text/plain
            text/xml;
        
        location /health {
            access_log off;
            proxy_pass http://api_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
        
        location /api/v1/auth {
            limit_req zone=auth_limit burst=5 nodelay;
            proxy_pass http://api_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_connect_timeout 5s;
            proxy_send_timeout 60s;
            proxy_read_timeout 60s;
        }
        
        location / {
            limit_req zone=api_limit burst=20 nodelay;
            proxy_pass http://api_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_connect_timeout 5s;
            proxy_send_timeout 60s;
            proxy_read_timeout 60s;
            
            # Enable keepalive
            proxy_http_version 1.1;
            proxy_set_header Connection "";
        }
    }