# IMPORTANT: This file contains template secrets for development
# In production, use proper secret management (HashiCorp Vault, AWS Secrets Manager, etc.)
# Never commit real secrets to version control

apiVersion: v1
kind: Secret
metadata:
  name: nyt-api-secrets
  namespace: nyt-news-api
  labels:
    app: nyt-api
    version: v1.0.0
  annotations:
    description: "API secrets - use proper secret management in production"
type: Opaque
stringData:
  # JWT Secret (256+ bits)
  JWT_SECRET: "your-super-secure-jwt-secret-key-must-be-at-least-256-bits-long-change-this-in-production"
  
  # OAuth Secrets
  OAUTH_CLIENT_ID: "your-oauth-client-id"
  OAUTH_CLIENT_SECRET: "your-oauth-client-secret"
  
  # Redis Password
  REDIS_PASSWORD: "your-redis-password"
  
  # Database URL (if using database)
  DATABASE_URL: "postgresql://username:password@postgres-service:5432/nyt_api"
  
  # External API Keys
  NYT_API_KEY: "your-nyt-api-key"
  
  # TLS Certificates (if using custom certs)
  TLS_CERT: |
    -----BEGIN CERTIFICATE-----
    # Your TLS certificate content here
    -----END CERTIFICATE-----
  
  TLS_KEY: |
    -----BEGIN PRIVATE KEY-----
    # Your TLS private key content here
    -----END PRIVATE KEY-----
---
# Service Account for Pod Identity
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nyt-api-sa
  namespace: nyt-news-api
  labels:
    app: nyt-api
  annotations:
    # For cloud provider integration (AWS IRSA, GCP Workload Identity, etc.)
    # eks.amazonaws.com/role-arn: "arn:aws:iam::ACCOUNT_ID:role/nyt-api-role"
    # iam.gke.io/gcp-service-account: "nyt-api@PROJECT_ID.iam.gserviceaccount.com"
automountServiceAccountToken: false  # Security: don't mount SA token unless needed