import { zodToTs } from "zod-to-ts";
import { schemas } from "../src/schemas/zod";
import * as fs from "fs";
import * as path from "path";

const allTypes: string[] = [];

for (const [name, schema] of Object.entries(schemas)) {
  const result = zodToTs(schema, name);
  allTypes.push(result.node.getText()); // ✅ Correct usage for ts-morph nodes
}

const outputPath = path.join(__dirname, "../src/types/nyt.ts");

fs.writeFileSync(
  outputPath,
  `// AUTO-GENERATED by scripts/gen-types.ts\n\n${allTypes.join("\n\n")}\n`
);

console.log(
  `✅ Wrote ${Object.keys(schemas).length} types to src/types/nyt.ts`
);
