swagger: '2.0'
basePath: /svc/archive/v1
host: api.nytimes.com
info:
  version: 2.0.0
  title: Archive
  description: |
    See `/src/external-apis/nyt/archive-product.yaml` for full source. This is a stub placeholder to load in Swagger UI.
schemes:
  - https
produces:
  - application/json
paths:
  '/{year}/{month}.json':
    get:
      summary: Archive month
      parameters:
        - name: year
          in: path
          required: true
          type: integer
        - name: month
          in: path
          required: true
          type: integer
      responses:
        '200':
          description: Success

