swagger: '2.0'
basePath: /svc/movies/v2
host: api.nytimes.com
info:
  version: 2.0.0
  title: Movie Reviews API (Deprecated)
  description: |
    See `/src/external-apis/nyt/movie-reviews-api.yaml` for full source. This is a stub placeholder to load in Swagger UI.
schemes:
  - https
produces:
  - application/json
paths: {}

