name: CI

on:
  push:
    branches: ['**']
  pull_request:

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Debug npm config
        run: |
          npm config list
          echo "Repo .npmrc:"; [ -f .npmrc ] && cat .npmrc || echo "(none)"
      
      - name: Force public registry
        run: |
          echo "registry=https://registry.npmjs.org/" > .npmrc
          cat .npmrc

      - name: Install
        run: npm ci

      - name: Test (coverage)
        env:
          CI: true
        run: |
          if npm run | grep -q "test:cov"; then
            npm run test:cov
          else
            # Fallback for CRA
            npm test -- --coverage --watchAll=false
          fi

      - name: Build
        env:
          CI: true
          REACT_APP_NYT_API_KEY: ${{ secrets.NYT_API_KEY }}
        run: npm run build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: build

      - name: Upload coverage
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage
