name: Build and Deploy
on:
  workflow_run:
    workflows: ["Tests"]
    types:
      - completed

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Configure npm registry
        run: npm config set registry https://registry.npmjs.org/

      - name: Install Dependencies
        run: bun install

      - name: Generate Types
        run: bun run gen:types

      - name: Build React App
        run: bun run build

      - name: Deploy to Hostinger via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./build/
          server-dir: public_html/
          protocol: ftp
          log-level: verbose
