name: Build and Deploy
on:
  workflow_run:
    workflows: ["Tests"]
    types:
      - completed

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Configure npm registry
        run: |
          # Clear any npm-related environment variables
          unset NPM_CONFIG_REGISTRY || true
          unset NPM_CONFIG_AUTH_TOKEN || true
          unset NPM_CONFIG_ALWAYS_AUTH || true
          
          # Clear npm config
          npm config delete registry
          npm config set registry https://registry.npmjs.org/
          npm config delete //artifactory.nordstrom.com/artifactory/api/npm/npm/:_authToken
          npm config delete //artifactory.nordstrom.com/artifactory/api/npm/npm/:always-auth
          
          # Verify configuration
          echo "NPM Registry Configuration:"
          npm config list
          echo "Environment variables:"
          env | grep -i npm || echo "No npm environment variables found"

      - name: Install Dependencies
        run: |
          # Clear bun cache to ensure fresh install
          bun pm cache rm
          # Install dependencies
          bun install

      - name: Generate Types
        run: bun run gen:types

      - name: Build React App
        run: bun run build

      - name: Deploy to Hostinger via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./build/
          server-dir: public_html/
          protocol: ftp
          log-level: verbose
