name: Deploy React App to Hostinger
on:
  push:
    branches: [master, main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build React app
        env:
          REACT_APP_NYT_API_KEY: ${{ secrets.REACT_APP_NYT_API_KEY }}
        run: |
          npm run build
          ls -la build/
          du -sh build/

      - name: Deploy to Hostinger via lftp (force mirror overwrite + delete)
        env:
          FTP_SERVER: ${{ secrets.FTP_SERVER }}
          FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
          REMOTE_DIR: /domains/brainvaultdev.com/public_html/nyt/
        run: |
          sudo apt-get update -y
          sudo apt-get install -y lftp
          echo "Deploying build/ to $REMOTE_DIR using lftp (force overwrite + delete)..."
          lftp -e "
            set xfer:temp-file-name \"\";
            set ftp:passive-mode yes;
            set ftp:ssl-allow no;
            set net:max-retries 2;
            set net:timeout 60;
            set xfer:clobber on;
            open -u $FTP_USERNAME,$FTP_PASSWORD $FTP_SERVER;
            mkdir -p $REMOTE_DIR;
            mirror -R --delete --ignore-time --overwrite --parallel=8 --verbose ./build $REMOTE_DIR;
            cls -l $REMOTE_DIR;
            quit
          "

      - name: Wait for deployment
        run: |
          echo "Waiting for deployment to complete..."
          sleep 10

      - name: Test deployment
        run: |
          echo "Testing deployment..."

          # Test if the app is accessible
          response=$(curl -s -o /dev/null -w "%{http_code}" https://nyt.brainvaultdev.com/ || echo "000")
          echo "Deployment test response: $response"

          if [ "$response" = "200" ]; then
            echo "✅ Deployment appears successful"
          else
            echo "⚠️  Deployment test returned $response - this might be due to caching"
            echo "Please check manually at https://nyt.brainvaultdev.com/"
          fi

      - name: Deployment Summary
        run: |
          echo "🚀 Deployment Summary:"
          echo "App URL: https://nyt.brainvaultdev.com/"
          echo "Search URL: https://nyt.brainvaultdev.com/search"
          echo ""
          echo "If you don't see the updated app, try:"
          echo "1. Clear your browser cache (Ctrl+Shift+R or Cmd+Shift+R)"
          echo "2. Check Hostinger's Cache Manager in hPanel"
          echo "3. Wait a few minutes for CDN cache to clear"
          echo ""
          echo "Hostinger Cache Manager:"
          echo "- Go to Websites → Dashboard → Cache Manager"
          echo "- Toggle 'Automatic cache' off and on"
          echo "- Or manually purge cache for the domain"
